version: "3"

services:
  db:
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env.backend
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
